services:
  node1:
    build: .
    environment:
      - NODE_ID=1
      - PORT=50051
      - PEERS=node2:50052,node3:50053
    ports:
      - "50051:50051"

  node2:
    build: .
    environment:
      - NODE_ID=2
      - PORT=50052
      - PEERS=node1:50051,node3:50053
    ports:
      - "50052:50052"

  node3:
    build: .
    environment:
      - NODE_ID=3
      - PORT=50053
      - PEERS=node1:50051,node2:50052
    ports:
      - "50053:50053"
